# observability-n-monitoring/ansible/playbooks/site.yaml

---
# =============================================================
# site.yaml - Master Playbook
# Complete deployment of K3s cluster + Observability stack
# =============================================================
# Run: ansible-playbook playbooks/site.yaml --ask-become-pass
#
# Run specific sections:
# Only prepare nodes
# ansible-playbook playbooks/site.yaml --tags prepare --ask-become-pass
#
# Skip specific sections:
# Run everything except ArgoCD
# ansible-playbook playbooks/site.yaml --skip-tags app --ask-become-pass
#
# To run specific sections only, use tags:
#   --tags prepare          : OS preparation only
#   --tags k3s              : K3s cluster only
#   --tags metallb          : MetalLB only
#   --tags observability    : Monitoring stack only
#   --tags app              : ArgoCD + Python app only
# =============================================================

- name: 00 - Verify all nodes are reachable
  ansible.builtin.import_playbook: 00_ping_test.yaml
  tags: [ping]

- name: 01 - Prepare all nodes for K3s
  ansible.builtin.import_playbook: 01_prepare_nodes.yaml
  tags: [prepare]

- name: 02 - Install K3s HA control plane
  ansible.builtin.import_playbook: 02_install_k3s_server.yaml
  tags: [k3s, servers]

- name: 03 - fetch kubeconfig
  ansible.builtin.import_playbook: 03_fetch_kubeconfig.yml
  tags: [fetch, kubeconfig]
  
- name: 04 - Join K3s worker nodes
  ansible.builtin.import_playbook: 04_install_k3s_agent.yaml
  tags: [k3s, agents]

- name: 05 - Install MetalLB for bare-metal LoadBalancer
  ansible.builtin.import_playbook: 05_install_metallb.yaml
  tags: [metallb]
  # Remember to install kubernetes. Use the below:
  # To check if present >
  # python3 -c "import kubernetes; print(kubernetes.__version__)" 2>&1
  # pip3 list 2>/dev/null | grep kubernetes
  # apt list --installed 2>/dev/null | grep python3-kubernetes
  # To install >
  # sudo apt update
  # sudo apt install -y python3-kubernetes python3-yaml

- name: 06 - Deploy observability stack
  ansible.builtin.import_playbook: 06_deploy_observability.yaml
  tags: [observability]

- name: 07 - Deploy ArgoCD and Python app (GitOps)
  ansible.builtin.import_playbook: 07_deploy_argocd_&_configure_python_app_gitops.yaml
  tags: [app, argocd]


# Execution Flow
#   00_ping_test
#    │
#    V
# 01_prepare_nodes       ← All 5 nodes (OS, firewall, swap, sleep)
#    │
#    V
# 02_install_k3s_server  ← controller1, controller2, controller3
#    │
#    V
# 03_install_k3s_agent   ← laptop-worker-1, laptop-worker-2
#    │
#    V
# 04_install_metallb     ← localhost (MetalLB + IP pool)
#    │
#    V
# 05_deploy_observability ← localhost (Prometheus, Grafana, Loki, Ingress)
#    │
#    V
# 06_deploy_argocd_app   ← localhost (ArgoCD + Python app GitOps)
#    │
#    V
# Cluster ready!