# observability-n-monitoring/kubernetes/python-app/prometheusrule.yaml

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: observability-app-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: app
      rules:
        - alert: HighErrorRate
          expr: |
            (sum(rate(http_requests_total{app="observability-app",status=~"5.."}[5m])) by (endpoint) / sum(rate(http_requests_total{app="observability-app"}[5m])) by (endpoint)) > 0.05
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "High error rate on {{ $labels.endpoint }}"
            description: "Error rate is {{ $value | humanizePercentage }}"