# monitoring/ansible/inventory/production/inventory.yaml

---
all:
  vars:
    ansible_user: ken
    ansible_ssh_private_key_file: ~/.ssh/cluster_id_ed25519
    ansible_python_interpreter: /usr/bin/python3
    
    

  children:
    k3s_server:
      hosts:
        controller1:
          ansible_host: 192.168.1.45
          node_type: server
          server_init: true             # First server initializes the cluster
        controller2:
          ansible_host: 192.168.1.57
          node_type: server
          server_init: false
        controller3:
          ansible_host: 192.168.1.48
          node_type: server
          server_init: false
      
    k3s_agent:
      hosts:
        laptop-worker-1:
          ansible_host: 192.168.1.183
          node_type: agent
        laptop-worker-2:
          ansible_host: 192.168.1.250
          node_type: agent